
name: PurgeCache
on:
  push:
    branches: [ main ]
    paths:
      - 'packages.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'packages.yaml'
jobs:
  purgeCache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PurgeJsDelivrCache
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: "https://purge.jsdelivr.net/gh/whwlsfb/BurpCrypto-JsLibrary/packages.yaml"
          method: "GET"
          timeout: 300000
